name: iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Build SmartFormApp
      run: |
        xcodebuild -project SmartFormApp.xcodeproj \
                   -scheme SmartFormApp \
                   -destination 'platform=iOS Simulator,name=iPhone 15' \
                   clean build
